<<: &shared
  language_name: SENĆOŦEN
mappings:
  - display_name: SENĆOŦEN equivalency
    mapping: str_equiv.json
    in_lang: str
    out_lang: str-equiv
    rule_ordering: as-written
    norm_form: NFC
    case_sensitive: false
    authors:
      - Shankhalika Srikanth
    <<: *shared
  - display_name: SENĆOŦEN to IPA
    mapping: str_to_ipa.json
    in_lang: str-equiv
    out_lang: str-ipa
    rule_ordering: as-written
    norm_form: NFC
    case_sensitive: false
    prevent_feeding: true
    authors:
      - Aidan Pine
    <<: *shared
