<<: &shared
  language_name: Cantonese
mappings:
  - display_name: Cantonese Jyutping to IPA
    in_lang: yue
    out_lang: yue-ipa
    authors:
      - Sabrina Yu
    type: mapping
    mapping: gwi_to_ipa.json
    prevent_feeding: true
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFD
    <<: *shared
    
