<<: &shared
  language_name: Northern Tutchone
mappings:
  - display_name: Northern Tutchone normalization
    in_lang: ttm
    out_lang: ttm-norm
    authors:
      - Shankhalika Srikanth
    type: mapping
    mapping: ttm_norm.csv
    prevent_feeding: false
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFC
    <<: *shared
  - display_name: Northern Tutchone to IPA
    in_lang: ttm-norm
    out_lang: ttm-ipa
    authors:
      - Shankhalika Srikanth
    type: mapping
    mapping: ttm_to_ipa.csv
    prevent_feeding: true
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFD
    <<: *shared
