<<: &shared
  language_name: Upper Tanana
mappings:
  - display_name: Upper Tanana Equivalencies
    in_lang: tau
    out_lang: tau-equiv
    authors:
      - Sabrina Yu
    type: mapping
    mapping: tau_equiv.csv
    prevent_feeding: true
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFD
    <<: *shared
  - display_name: Upper Tanana to Simplified
    in_lang: tau-equiv
    out_lang: tau-simp
    authors:
      - Sabrina Yu
    type: mapping
    mapping: tau_simplify.json
    prevent_feeding: true
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFD
    <<: *shared
  - display_name: Upper Tanana to IPA
    in_lang: tau-simp
    out_lang: tau-ipa
    authors:
      - Sabrina Yu
    type: mapping
    mapping: tau_to_ipa.json
    prevent_feeding: true
    rule_ordering: as-written
    case_sensitive: false
    norm_form: NFD
    <<: *shared
    